### ISSUE TITLE
Can you share your dataset used in the paper like folders of image classes?

### ISSUE THREAD

**Issue by linhduongtuan** [ufopcsilab/EfficientNet-C19#1]
Dear researchers,
I am interested in your paper "Towards an Efficient Deep Learning Model for
COVID-19 Patterns Detection in X-ray Images". And I'd like to improve performance of CNNs.
So can you share your final dataset in format of folders like Covid-19 (contain covid-19 X ray images), Normal (consist of normal X ray images), and so on.
Best regards
Linh

**Comment by zeeshannisar** [comment]
@linhduongtuan you can check at [Here](https://drive.google.com/drive/folders/1_gVN0-3_2XmKl9171WMnRsHBUt7eeWuQ?usp=sharing) for your issue.

**Comment by linhduongtuan** [comment]
Many thank for your sharing. I got it and have a webapp to diagnose Covid-19 based on dataset here https://covidresearch.ai/datasets/dataset?id=2.
I think, my model was trained with a lit bit better optimization than the results showed in paper https://arxiv.org/pdf/2004.05717.pdf.
Linh
