### ISSUE TITLE
Dataset Needed

### ISSUE THREAD

**Issue by Akhilesh133** [ufopcsilab/EfficientNet-C19#2]
Hello Researcher,

I was trying to download the dataset that u were using. I would be great if i can get the link to the dataset and i have hard time trying to figure it out. It would be great if you could provide link to the dataset.

**Comment by silvaphl** [comment]
Hi,

We used the COVIDx dataset. The dataset was proposed initially in this repository [lindawangg/COVID-Net](https://github.com/lindawangg/COVID-Net).

Best regards.
